language: python

python:
 - "3.5"

addons:
  apt:
    packages:
    - git

install:
  # Clone oq-engine
  - git clone -q --depth=1 https://github.com/gem/oq-engine.git
  # Install oq-engine dependencies
  - pip -q install -r oq-engine/requirements-py35-linux64.txt
  # Install package dependencies
  - pip install -r requirements.txt

script:
  - nosetests -vx oq/hmtk/tests
